let dollar_rate = 43.7;
let euro_rate = 51.2;
let income_1 = 100000;
let income_2 = 200000;
let income_3 = 300000;
let income_4 = 150000;
let total_income = income_1 + income_2 + income_3 + income_4;
let single_tax = total_income * 0.05;
let esv = 18000;
let income_after_taxes = total_income - single_tax - esv;
let sback_alive = income_after_taxes * 0.10;
let schildren_of_heroes = income_after_taxes * 0.05;
let business_dev = 100000;
let currency_savings = (2500 * euro_rate) + (3000 * dollar_rate);
let balance = income_after_taxes - sback_alive - schildren_of_heroes - business_dev - currency_savings;
console.log(`За рік Максим заробив - ${total_income} грн`);
console.log(`Єдиний податок 5% складає ${single_tax} грн`);
console.log(`Відрахування у фонди ""Повернись живим" та "Діти Героїв"" складає ${sback_alive} грн та ${schildren_of_heroes} грн відповідно`);
console.log(`На валютну карту сумарно відкладено ще ${currency_savings} грн`);
console.log(`Залишок на рахунку Максима складає ${balance} грн`);
